- name: Create folder
  file:
    path: "{{ generator_release_path }}"
    state: directory

# get_url does not work - redmine fails to respond with 401 to trigger basic_auth in urllib2
- name: Download archive
  shell: "curl -u{{ generator_archive_user }}:{{ generator_archive_password }} {{ generator_archive_url }} -o{{ generator_release_path }}/{{ generator_archive_name }}"
  args:
    creates: "{{ generator_release_path }}/{{ generator_archive_name }}"

- name: Extract archive
  shell: "7z x {{ generator_archive_name }}"
  args:
    chdir: "{{ generator_release_path }}"
    creates: "{{ generator_release_path }}/generator"

- name: Link to current deploy
  file:
    path: "{{ generator_current_path }}"
    src: "{{ generator_release_path }}/generator/bin/"
    state: link
    force: true
  notify:
  - restart generator

- name: Export environment
  shell: "./generator --exportEnvironment {{ generator_current_path }}/environment"
  args:
    chdir: "{{ generator_current_path }}"
    creates: "{{ generator_current_path }}/environment"
