- name: Install vim
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - vim

- name: Create folder
  file:
    path: "{{ deploy_path | default(app_path, true) }}{{ item }}"
    owner: "{{ deploy_owner | default(app_user, true) }}"
    group: "{{ deploy_group | default(app_user, true) }}"
    state: directory
  with_items: deploy_create_folders

- name: Setup Logrotate
  template:
    dest: "/etc/logrotate.d/{{ app_name }}"
    src: "logrotate.j2"
