#
# perform a bundle run
#
---
- name: Bundle install
  shell: >
    {{ ruby_bin }}bundle install
    --binstubs {{ bundle_binstubs | default(app_path + '/shared/bin', true) }}
    --gemfile {{ bundle_gemfile }}
    --path {{ bundle_path | default(app_path + '/shared/bundle', true) }}
    --without {{ bundle_without | join(' ') }}
    {{ bundle_flags | join(' ') }}
  args:
    chdir: "{{ RELEASE_PATH }}"
  register: result
  changed_when: "'Installing' in result.stdout"
  notify:
  - restart required
