#
# Create the base structure for the release
#
- name: Create folders
  file:
    path: "{{ rails_deploy_path | default(app_path, true) }}/{{ item }}"
    owner: "{{ rails_deploy_owner | default(app_user, true) }}"
    group: "{{ rails_deploy_group | default(app_user, true) }}"
    state: directory
  with_items: rails_deploy_create_folders
