---
- hosts:
  - app
  sudo: yes
  sudo_user: '{{ app_user }}'
  remote_user: '{{ app_user }}'

  vars:
    profile: '/bin/bash -lc -- '

  pre_tasks:
  - name: Check previous deploy
    stat:
      path: "{{ app_path }}/current"
    register: deploy_current

  - set_fact:
      run_restart: "{{ deploy_current.stat.exists }}"

  - name: Trigger restart
    file:
      path: "{{ app_path }}/shared/tmp/restart.txt"
      state: touch
    when: run_restart | bool

  roles:
  - role: dresden-weekly.Rails/webrick/restart
    when: run_restart | bool
