---
- hosts:
  - app
  sudo: yes
  sudo_user: '{{ app_user }}'
  remote_user: '{{ app_user }}'

  vars:
    profile: '/bin/bash -lc -- '
    was_provisioned: "{{ provisioned if provisioned is defined else false }}"
    was_allow_vagrant: "{{ allow_vagrant if allow_vagrant is defined else false }}"
    is_vagrant: "{{ 'vagrant' in groups }}"

  pre_tasks:
  - name: Check previous deploy
    stat:
      path: "{{ app_path }}/current"
    register: deploy_current
    tags:
    - facts

  - set_fact:
      not_provisioned: "{{ not (was_provisioned | bool) }}"
      use_vagrant_folder: "{{ (was_allow_vagrant | bool) and (is_vagrant | bool) and (was_provisioned | bool) }}"
      is_first_deploy: "{{ not deploy_current.stat.exists }}"
    tags:
    - facts

  - set_fact:
      run_deploy: "{{ (is_first_deploy | bool) or (not_provisioned | bool) or (use_vagrant_folder | bool) }}"
    tags:
    - facts

  roles:
  - dresden-weekly.Rails/rails/folders

  - role: dresden-weekly.Rails/rails/use-vagrant
    when: (run_deploy | bool) and (use_vagrant_folder | bool)

  - role: dresden-weekly.Rails/rails/create-release
    rails_deploy_custom_archive:
    - Gemfile.lock
    when: (run_deploy | bool) and not (use_vagrant_folder | bool)

  - role: dresden-weekly.Rails/rails/tasks/bundle
    bundle_flags:
    - '--quiet'
    - '--deployment'
    when: run_deploy | bool

  - role: dresden-weekly.Rails/rails/tasks/migrate-database
    when: run_deploy | bool

  - role: dresden-weekly.Rails/rails/tasks/compile-assets
    when: run_deploy | bool

  - role: dresden-weekly.Rails/rails/update-current
    when: run_deploy | bool

  - role: dresden-weekly.Rails/webrick/restart
    when: run_deploy | bool

  - role: dresden-weekly.Rails/rails/cleanup-old-releases
    when: run_deploy | bool
