---
- hosts: app
  sudo: yes
  roles:
  - dresden-weekly.Rails/postgresql
  - role: dresden-weekly.Rails/create-user
    user:
      name: "{{ app_user }}"
      authorized_keys:
      - "{{ lookup('file', '../id_rsa.pub') }}"
      bashrc_lines:
      - "cd {{ app_path }} || true"
      - "cd {{ app_path }}/current || true"
      env:
        SECRET_KEY_BASE: "{{ app_secret_key_base }}"
        RAILS_LOG_FILE_PATH: "{{ app_path }}/shared/log/"
        DATABASE_URL: "{{ DATABASE_URL }}"
  - dresden-weekly.Rails/rails/create-folders
  - dresden-weekly.Rails/rails/logrotate
  - dresden-weekly.Rails/ruby/rvm
  - dresden-weekly.Rails/ruby/postgresql
  - role: dresden-weekly.Rails/upstart/userjobs
    users:
    - "{{ app_user }}"
  - dresden-weekly.Rails/webrick/upstart
  - dresden-weekly.Rails/nginx/server
  - dresden-weekly.Rails/nginx/webrick

- include: deploy.yml
  sudo: yes
  sudo_user: "{{ app_user }}"
  vars:
    provisioned: yes
