---
- hosts: app
  become: yes

  pre_tasks:
    - user:
        name:   "{{ app_user }}"
        groups: "www-data"
        state:  "present"

  roles:
  - dresden-weekly.Rails/postgresql

  - dresden-weekly.Rails/ruby/rvm
  - dresden-weekly.Rails/ruby/postgresql
  - dresden-weekly.Rails/ruby/sqlite3

  - dresden-weekly.Rails/rails/folders
  - dresden-weekly.Rails/rails/logrotate

  - role: dresden-weekly.Rails/user/profile
    rails_user_name: "{{ app_user }}"
    rails_user_bashrc_lines:
    - "cd {{ RAILS_APP_BASE_PATH }} || true"
    - "cd {{ RAILS_APP_CURRENT_PATH }} || true"
    rails_user_env:
      RAILS_ENV: "{{ rails_env }}"
      SECRET_KEY_BASE: "{{ app_secret_key_base }}"
      RAILS_LOG_FILE_PATH: "{{ RAILS_APP_LOG_PATH }}"
      DATABASE_URL: "{{ DATABASE_URL }}"

  - role: dresden-weekly.Rails/upstart/userjobs
    users:
    - "{{ app_user }}"
  - dresden-weekly.Rails/webrick/service
  - dresden-weekly.Rails/nginx/server
  - dresden-weekly.Rails/nginx/webrick

- include: deploy.yml
  vars:
    provisioned: yes
