---
- hosts: db
  become: yes
  vars:
    _: &bashrc_lines
    - "cd {{ app_path }} || true"
    - "cd {{ app_path }}/current || true"

  roles:
  - dresden-weekly.Rails/postgresql

- hosts: app
  become: yes

  pre_tasks:
    - user:
        name: "{{ app_user }}"
        groups: "www-data"
        state: "present"
        shell: "/bin/bash"

  roles:
  - role: dresden-weekly.Rails/ssh_agent
    run_once: yes
    delegate_to: 127.0.0.1

  - dresden-weekly.Rails/ruby/rvm
  - dresden-weekly.Rails/ruby/postgresql
  - dresden-weekly.Rails/ruby/sqlite3

  - dresden-weekly.Rails/rails/folders
  - dresden-weekly.Rails/rails/logrotate

  - role: dresden-weekly.Rails/user/profile
    rails_user_name: "{{ app_user }}"
    rails_user_bashrc_lines: *bashrc_lines
    rails_user_env:
      RAILS_ENV: "{{ rails_env }}"
      SECRET_KEY_BASE: "{{ app_secret_key_base }}"
      RAILS_LOG_FILE_PATH: "{{ app_path }}/shared/log/"
    rails_user_env_facts:
    - group: db
      index: 0
      facts:
      - DATABASE_URL


  - dresden-weekly.Rails/git/env-credentials

  - role: dresden-weekly.Rails/upstart/userjobs
    users:
    - "{{ app_user }}"
  - dresden-weekly.Rails/webrick/service

- hosts: web
  become: yes

  pre_tasks:
    - user:
        name: "{{ app_user }}"
        groups: "www-data"
        state: "present"
        shell: "/bin/bash"

  roles:
  - role: dresden-weekly.Rails/user/profile
    rails_user_name: "{{ app_user }}"
    rails_user_bashrc_lines: *bashrc_lines
    rails_user_env:
      SECRET_KEY_BASE: "{{ app_secret_key_base }}"
      RAILS_LOG_FILE_PATH: "{{ app_path }}/shared/log/"

  - dresden-weekly.Rails/rails/folders
  - dresden-weekly.Rails/nginx/server
  - dresden-weekly.Rails/nginx/webrick

- include: deploy.yml
  vars:
    provisioned: yes
