---
- hosts:
  - app
  - web
  sudo: yes
  sudo_user: '{{ app_user }}'
  remote_user: '{{ app_user }}'

  vars:
    ruby_bin: '~/.rvm/bin/rvm default do '
    profile: '. $HOME/.profile && sh $HOME/.profile && '
    is_vagrant: "{{ 'vagrant' in groups }}"

  pre_tasks:
  - name: Check previous deploy
    stat:
      path: "{{ app_path }}/current"
    register: deploy_current

  - set_fact:
      run_deploy: "{{ not (is_vagrant | bool) and (deploy_current.stat.exists) }}"

  roles:
  - role: dresden-weekly.Rails/deploy/revert
    when: run_deploy | bool

  - role: dresden-weekly.Rails/deploy/rails
    when: run_deploy | bool

  - role: dresden-weekly.Rails/deploy/finish
    when: run_deploy | bool

  - role: dresden-weekly.Rails/webrick/restart
    when: run_deploy | bool
