---
- name: Define release id
  set_fact:
    RELEASE_ID: "{{ [ansible_date_time.year, ansible_date_time.month, ansible_date_time.day, ansible_date_time.hour, ansible_date_time.minute, ansible_date_time.second] | join('') }}"

- name: Ensure git mirror repo is up to date
  git:
    repo: "{{ git_url }}"
    dest: "{{ app_path }}/repo"
    bare: yes
    version: "{{ git_branch }}"
    update: yes
    accept_hostkey: yes
  remote_user: "{{ app_user }}"

- name: Create release
  shell: "git archive --format=tar --prefix={{ RELEASE_ID }}/ {{ git_branch }} {{ deploy_rails_archive | join(' ') }} {{ deploy_custom_archive | join(' ') }} | (cd {{ app_path }}/releases && tar -xf -)"
  args:
    creates: "{{ app_path }}/releases/{{ RELEASE_ID }}"
    chdir: "{{ app_path }}/repo"

- name: Clean shared folders
  file:
    path: "{{ app_path }}/releases/{{ RELEASE_ID }}/{{ item }}"
    state: absent
    force: yes
  with_flattened:
  - deploy_shared_rails_folders
  - deploy_shared_custom_folders

- name: Create custom folders
  file:
    path: "{{ app_path }}/releases/{{ RELEASE_ID }}/{{ item }}"
    state: directory
  with_flattened:
  - deploy_create_custom_folders

- include: shared_folders.yml
