---
- name: Create shared folders
  file:
    path: "{{ app_path }}/shared/{{ item }}"
    state: directory
  with_flattened:
  - deploy_shared_rails_folders
  - deploy_shared_custom_folders

- name: Link shared folders
  file:
    path: "{{ app_path }}/releases/{{ RELEASE_ID }}/{{ item }}"
    src: "{{ app_path }}/shared/{{ item }}"
    state: link
    force: yes
  with_flattened:
  - deploy_shared_rails_folders
  - deploy_shared_custom_folders
