---
- name: Bundle install
  shell: >
    {{ ruby_bin }}bundle install
    --binstubs {{ bundle_binstubs | default(app_path + '/shared/bin', true) }}
    --gemfile {{ bundle_gemfile }}
    --path {{ bundle_path | default(app_path + '/shared/bundle', true) }}
    --without {{ bundle_without | join(' ') }}
    {{ bundle_flags | join(' ') }}
  args:
    chdir: "{{ app_path }}/releases/{{ RELEASE_ID }}"
  register: bundle_install_result
  changed_when: "'Installing' in bundle_install_result.stdout"
  notify:
  - restart required

- name: Precompile assets
  shell: "{{ profile }}{{ ruby_bin }}bundle exec rake assets:precompile"
  args:
    chdir: "{{ app_path }}/releases/{{ RELEASE_ID }}"
  when: (inventory_hostname in groups['web']) and (compile_assets | bool)
  register: precompile_assets_result
  changed_when: "'Writing' in precompile_assets_result.stdout"

- name: Migrate database
  shell: "{{ profile }}{{ ruby_bin }}bundle exec rake db:migrate"
  args:
    chdir: "{{ app_path }}/releases/{{ RELEASE_ID }}"
  when: inventory_hostname == groups['app'][0]
  register: migrate_database_result
  changed_when: "'migrating' in migrate_database_result.stdout"
  notify:
  - restart required
