---
- hosts:
  - app
  - web
  sudo: yes
  sudo_user: '{{ app_user }}'
  remote_user: '{{ app_user }}'

  vars:
    ruby_bin: '~/.rvm/bin/rvm default do '
    profile: '. $HOME/.profile && /bin/bash $HOME/.profile && '
    was_provisioned: "{{ provisioned if provisioned is defined else false }}"
    was_allow_vagrant: "{{ allow_vagrant if allow_vagrant is defined else false }}"
    is_vagrant: "{{ 'vagrant' in groups }}"

  pre_tasks:
  - name: Check previous deploy
    stat:
      path: "{{ app_path }}/current"
    register: deploy_current

  - set_fact:
      not_provisioned: "{{ not (was_provisioned | bool) }}"
      use_vagrant_folder: "{{ (was_allow_vagrant | bool) and (is_vagrant | bool) and (was_provisioned | bool) }}"
      is_first_deploy: "{{ not deploy_current.stat.exists }}"

  - set_fact:
      run_deploy: "{{ (is_first_deploy | bool) or (not_provisioned | bool) or (use_vagrant_folder | bool) }}"

  roles:
  - role: dresden-weekly.Rails/rails/use-vagrant
    when: (run_deploy | bool) and (use_vagrant_folder | bool)

  - role: dresden-weekly.Rails/rails/create-release
    when: (run_deploy | bool) and not (use_vagrant_folder | bool)

  - role: dresden-weekly.Rails/rails/tasks/bundle
    when: run_deploy | bool

  - role: dresden-weekly.Rails/rails/tasks/migrate-database
    when: run_deploy | bool

  - role: dresden-weekly.Rails/rails/tasks/compile-assets
    when: run_deploy | bool

  - role: dresden-weekly.Rails/rails/update-current
    when: run_deploy | bool

  - role: dresden-weekly.Rails/puma/restart
    when: run_deploy | bool

  - role: dresden-weekly.Rails/rails/cleanup-old-releases
    when: run_deploy | bool
