---
- hosts:
  - app
  - web
  vars:
    remote_user: '{{ app_user }}'
    sudo: yes
    sudo_user: '{{ remote_user }}'
    ruby_bin: '~/.rvm/bin/rvm default do '
    profile: '. $HOME/.profile && sh $HOME/.profile && '
    was_provisioned: "{{ provisioned is defined }}"
    is_vagrant: "{{ 'vagrant' in groups }}"

  pre_tasks:
  - name: Check previous deploy
    stat:
      path: "{{ app_path }}/current"
    register: deploy_current

  - set_fact:
      not_provisioned: "{{ not (was_provisioned | bool) }}"
      use_vagrant_folder: "{{ (is_vagrant | bool) and (was_provisioned | bool) }}"
      is_first_deploy: "{{ not deploy_current.stat.exists }}"

  - set_fact:
      run_deploy: "{{ (is_first_deploy | bool) or (not_provisioned | bool) or (is_vagrant | bool) }}"
      run_import: "{{ (is_first_deploy | bool) or (is_vagrant | bool) }}"

  roles:
  - role: deploy/vagrant
    when: (run_deploy | bool) and (use_vagrant_folder | bool)

  - role: deploy/update
    when: (run_deploy | bool) and not (use_vagrant_folder | bool)

  - role: deploy/rails
    when: run_deploy | bool

  - role: deploy/finish
    when: run_deploy | bool

  - role: puma/restart
    when: run_deploy | bool
