---
- hosts: db
  vars:
    _: &app_user
      name: "{{ app_user }}"
      shell: /bin/bash
      authorized_key: "{{ lookup('file', 'id_rsa.pub') }}"
      bashrc_lines:
      - "cd {{ app_path }}"
      - "cd {{ app_path }}/current"

  roles:
  - dresden-weekly.Rails/postgresql

- hosts: app
  roles:
  - role: dresden-weekly.Rails/create-user
    user:
      <<: *app_user
      env:
        SECRET_KEY_BASE: "{{ app_secret_key_base }}"
        RAILS_LOG_FILE_PATH: "{{ app_path }}/shared/log/"
      env_facts:
      - group: db
        index: 0
        facts:
        - DATABASE_URL
  - dresden-weekly.Rails/rails/create-folders
  - dresden-weekly.Rails/rails/logrotate
  - dresden-weekly.Rails/ruby/rvm
  - dresden-weekly.Rails/ruby/postgresql
  - role: dresden-weekly.Rails/upstart/userjobs
    users:
    - "{{ app_user }}"
  - dresden-weekly.Rails/puma/upstart

- hosts: web
  roles:
  - role: create-user
    user: *app_user
  - dresden-weekly.Rails/rails/create-folders
  - dresden-weekly.Rails/ruby/rvm # required to compile assets
  - dresden-weekly.Rails/nginx/server
  - dresden-weekly.Rails/nginx/puma

- include: deploy.yml
  vars:
    provisioned: yes
    sudo: yes
    sudo_user: "{{ app_user }}"
