
# a documented example user
user:
  name: example # required!
  comment: Managed by Ansible # is the default
  password: '' # empty password by default
  shell: /bin/bash # default ist /bin/sh
  authorized_keys: [] # (.ssh/authorized_keys) default is ENV['AUTHORIZED_KEY']
  group: example # (main group of the user) default is the user name
  groups: [] # extra groups
  env: # (Environment variables added to .profile)
    DATABASE_URL: "..."
    PATH: "$HOME/.rvm/bin:$PATH" # useful for rvm_ruby
  env_facts: # (Facts added as environment variables)
  - group: db # (index to groups) required!
    index: 0 # (index inside the group) 0 is default
    facts: # (list of fact-names == variable name)
    - DATABASE_URL
  - group: app
    index: 0
    facts:
    - RAILS_LOG_FILE_PATH
  bashrc_lines: # lines added to the .bashrc file
  - cd /data/example_app
  - cd /data/example_app/current
